{
  "swagger": "2.0",
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "API Operations require a valid token."
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ],
  "paths": {
    "/users/sign-up": {
      "post": {
        "tags": [
          "Registration"
        ],
        "summary": "User registration",
        "responses": {
          "422": {
            "schema": {
              "$ref": "#/definitions/Error"
            },
            "description": "Unprocessable Entity"
          },
          "200": {
            "schema": {
              "$ref": "#/definitions/UserToken"
            },
            "description": "Ok"
          }
        },
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/UserRegisterRequest"
            },
            "required": true,
            "name": "user",
            "in": "body",
            "description": "User to register"
          }
        ],
        "operationId": "WraftDocWeb.Api.V1.RegistrationController.create",
        "description": "User registration API"
      }
    },
    "/users/sign-in": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "User sign in",
        "responses": {
          "422": {
            "schema": {
              "$ref": "#/definitions/Error"
            },
            "description": "Unprocessable Entity"
          },
          "200": {
            "schema": {
              "$ref": "#/definitions/UserToken"
            },
            "description": "Ok"
          }
        },
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/UserLoginRequest"
            },
            "required": true,
            "name": "user",
            "in": "body",
            "description": "User to trying to login"
          }
        ],
        "operationId": "WraftDocWeb.Api.V1.UserController.signin",
        "description": "User sign in API"
      }
    },
    "/layouts": {
      "post": {
        "tags": [
          "Layout"
        ],
        "summary": "Create layout",
        "responses": {
          "422": {
            "schema": {
              "$ref": "#/definitions/Error"
            },
            "description": "Unprocessable Entity"
          },
          "401": {
            "schema": {
              "$ref": "#/definitions/Error"
            },
            "description": "Unauthorized"
          },
          "200": {
            "schema": {
              "$ref": "#/definitions/LayoutAndEngine"
            },
            "description": "Ok"
          }
        },
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/LayoutRequest"
            },
            "required": true,
            "name": "layout",
            "in": "body",
            "description": "Layout to be created"
          }
        ],
        "operationId": "WraftDocWeb.Api.V1.LayoutController.create",
        "description": "Create layout API"
      }
    }
  },
  "info": {
    "version": "0.0.1",
    "title": "Wraft Docs"
  },
  "host": "localhost:4000",
  "definitions": {
    "UserToken": {
      "type": "object",
      "title": "User and token",
      "required": [
        "token"
      ],
      "properties": {
        "user": {
          "$ref": "#/definitions/User"
        },
        "token": {
          "type": "string",
          "description": "JWT token for authenticating the user"
        }
      },
      "example": {
        "user": {
          "updated_at": "2020-01-21T14:00:00Z",
          "name": "John Doe",
          "inserted_at": "2020-02-21T14:00:00Z",
          "id": "1232148nb3478",
          "email_verify": true,
          "email": "email@xyz.com"
        },
        "token": "Asdlkqweb.Khgqiwue132.xcli123"
      },
      "description": "User details with the generated JWT token for authentication"
    },
    "UserRegisterRequest": {
      "type": "object",
      "title": "Register User",
      "required": [
        "password",
        "email",
        "name"
      ],
      "properties": {
        "password": {
          "type": "string",
          "description": "User's password"
        },
        "name": {
          "type": "string",
          "description": "User's name"
        },
        "email": {
          "type": "string",
          "description": "User's email"
        }
      },
      "example": {
        "password": "Password",
        "name": "John Doe",
        "email": "email@xyz.com"
      },
      "description": "A user to be registered in the application"
    },
    "UserLoginRequest": {
      "type": "object",
      "title": "User Login",
      "required": [
        "password",
        "email"
      ],
      "properties": {
        "password": {
          "type": "string",
          "description": "User's password"
        },
        "email": {
          "type": "string",
          "description": "User's email"
        }
      },
      "example": {
        "password": "Password",
        "email": "email@xyz.com"
      },
      "description": "A user log in to the application"
    },
    "User": {
      "type": "object",
      "title": "User",
      "required": [
        "email",
        "name",
        "id"
      ],
      "properties": {
        "updated_at": {
          "type": "string",
          "format": "ISO-8601",
          "description": "When was the user last updated"
        },
        "name": {
          "type": "string",
          "description": "Users name"
        },
        "inserted_at": {
          "type": "string",
          "format": "ISO-8601",
          "description": "When was the user inserted"
        },
        "id": {
          "type": "string",
          "description": "The ID of the user"
        },
        "email_verify": {
          "type": "boolean",
          "description": "Email verification status"
        },
        "email": {
          "type": "string",
          "description": "Users email"
        }
      },
      "example": {
        "updated_at": "2020-01-21T14:00:00Z",
        "name": "John Doe",
        "inserted_at": "2020-02-21T14:00:00Z",
        "id": "1232148nb3478",
        "email_verify": true,
        "email": "email@xyz.com"
      },
      "description": "A user of the application"
    },
    "LayoutRequest": {
      "type": "object",
      "title": "Layout Request",
      "required": [
        "name"
      ],
      "properties": {
        "width": {
          "type": "float",
          "description": "Width of the layout"
        },
        "unit": {
          "type": "string",
          "description": "Unit of dimensions"
        },
        "slug": {
          "type": "string",
          "description": "Name of the slug to be used for the layout"
        },
        "name": {
          "type": "string",
          "description": "Layout's name"
        },
        "height": {
          "type": "float",
          "description": "Height of the layout"
        },
        "engine_id": {
          "type": "integer",
          "description": "ID of the engine selected"
        },
        "description": {
          "type": "string",
          "description": "Layout's description"
        }
      },
      "example": {
        "width": 40.0,
        "unit": "cm",
        "slug": "Pandoc",
        "name": "Official Letter",
        "height": 20.0,
        "engine_id": "1232148nb3478",
        "description": "An official letter"
      },
      "description": "Create layout request."
    },
    "LayoutAndEngine": {
      "type": "object",
      "title": "Layout",
      "required": [
        "name",
        "id"
      ],
      "properties": {
        "width": {
          "type": "float",
          "description": "Width of the layout"
        },
        "updated_at": {
          "type": "string",
          "format": "ISO-8601",
          "description": "When was the user last updated"
        },
        "unit": {
          "type": "string",
          "description": "Unit of dimensions"
        },
        "slug": {
          "type": "string",
          "description": "Name of the slug to be used for the layout"
        },
        "name": {
          "type": "string",
          "description": "Layout's name"
        },
        "inserted_at": {
          "type": "string",
          "format": "ISO-8601",
          "description": "When was the user inserted"
        },
        "id": {
          "type": "string",
          "description": "The ID of the layout"
        },
        "height": {
          "type": "float",
          "description": "Height of the layout"
        },
        "engine": {
          "$ref": "#/definitions/Engine"
        },
        "description": {
          "type": "string",
          "description": "Layout's description"
        }
      },
      "example": {
        "width": 40.0,
        "updated_at": "2020-01-21T14:00:00Z",
        "unit": "cm",
        "slug": "Pandoc",
        "name": "Official Letter",
        "inserted_at": "2020-02-21T14:00:00Z",
        "id": "1232148nb3478",
        "height": 20.0,
        "engine": {
          "updated_at": "2020-01-21T14:00:00Z",
          "name": "Pandoc",
          "inserted_at": "2020-02-21T14:00:00Z",
          "id": "1232148nb3478",
          "api_route": ""
        },
        "description": "An official letter"
      },
      "description": "Layout to be used for the generation of a document."
    },
    "Error": {
      "type": "object",
      "title": "Errors",
      "required": [
        "error"
      ],
      "properties": {
        "error": {
          "type": "string",
          "description": "The message of the error raised"
        }
      },
      "description": "Error responses from the API"
    },
    "Engine": {
      "type": "object",
      "title": "Render engine",
      "required": [
        "name",
        "id"
      ],
      "properties": {
        "updated_at": {
          "type": "string",
          "format": "ISO-8601",
          "description": "When was the user last updated"
        },
        "name": {
          "type": "string",
          "description": "Engine's name"
        },
        "inserted_at": {
          "type": "string",
          "format": "ISO-8601",
          "description": "When was the user inserted"
        },
        "id": {
          "type": "string",
          "description": "The ID of the engine"
        },
        "api_route": {
          "type": "string",
          "description": "API route to be used"
        }
      },
      "example": {
        "updated_at": "2020-01-21T14:00:00Z",
        "name": "Pandoc",
        "inserted_at": "2020-02-21T14:00:00Z",
        "id": "1232148nb3478",
        "api_route": ""
      },
      "description": "A render engine to be used for document generation"
    }
  },
  "basePath": "/api/v1"
}